<?php

namespace App\Services;

use App\Models\Order;

class OrderExportService
{
    protected $defaultFields = [
        'id',
        'order_number',
        'type',
        'name',
        'email',
        'phone',
        'telegram',
        'service',
        'subject',
        'amount',
        'status',
        'created_at',
    ];
    
    public function exportCsv($filters = [], $fields = null)
    {
        $fields = $fields ?? $this->defaultFields;
        $query = $this->buildQuery($filters);
        $orders = $query->get();
        
        $output = fopen('php://temp', 'r+');
        
        fputcsv($output, $this->formatHeaders($fields));
        
        foreach ($orders as $order) {
            $row = [];
            foreach ($fields as $field) {
                $row[] = $this->formatFieldValue($order, $field);
            }
            fputcsv($output, $row);
        }
        
        rewind($output);
        $csv = stream_get_contents($output);
        fclose($output);
        
        return $csv;
    }
    
    public function exportPdf($filters = [], $fields = null)
    {
        $fields = $fields ?? $this->defaultFields;
        $query = $this->buildQuery($filters);
        $orders = $query->get();
        
        $html = $this->generatePdfHtml($orders, $fields);
        
        return $this->convertHtmlToPdf($html);
    }
    
    protected function buildQuery($filters)
    {
        $query = Order::query();
        
        if (!empty($filters['status'])) {
            $query->status($filters['status']);
        }
        
        if (!empty($filters['type'])) {
            $query->type($filters['type']);
        }
        
        if (!empty($filters['date_from']) || !empty($filters['date_to'])) {
            $query->dateRange(
                $filters['date_from'] ?? null,
                $filters['date_to'] ?? null
            );
        }
        
        if (!empty($filters['search'])) {
            $query->search($filters['search']);
        }
        
        if (!empty($filters['form_slug'])) {
            $query->where('form_slug', $filters['form_slug']);
        }
        
        if (isset($filters['archived'])) {
            if ($filters['archived']) {
                $query->archived();
            } else {
                $query->active();
            }
        }
        
        $query->orderBy('created_at', 'desc');
        
        if (!empty($filters['limit'])) {
            $query->limit((int)$filters['limit']);
        }
        
        return $query;
    }
    
    protected function formatHeaders($fields)
    {
        $headers = [];
        foreach ($fields as $field) {
            $headers[] = ucwords(str_replace('_', ' ', $field));
        }
        return $headers;
    }
    
    protected function formatFieldValue($order, $field)
    {
        $value = $order->{$field};
        
        if (is_null($value)) {
            return '';
        }
        
        if ($value instanceof \Carbon\Carbon) {
            return $value->format('Y-m-d H:i:s');
        }
        
        if (is_array($value)) {
            return json_encode($value);
        }
        
        return $value;
    }
    
    protected function generatePdfHtml($orders, $fields)
    {
        $html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Orders Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10pt;
        }
        h1 {
            font-size: 16pt;
            margin-bottom: 20px;
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #4CAF50;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #ddd;
        }
        td {
            padding: 6px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 20px;
            font-size: 8pt;
            color: #666;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>Orders Export - ' . date('Y-m-d H:i:s') . '</h1>
    <table>
        <thead>
            <tr>';
        
        foreach ($fields as $field) {
            $html .= '<th>' . htmlspecialchars(ucwords(str_replace('_', ' ', $field))) . '</th>';
        }
        
        $html .= '</tr>
        </thead>
        <tbody>';
        
        foreach ($orders as $order) {
            $html .= '<tr>';
            foreach ($fields as $field) {
                $value = $this->formatFieldValue($order, $field);
                $html .= '<td>' . htmlspecialchars($value) . '</td>';
            }
            $html .= '</tr>';
        }
        
        $html .= '</tbody>
    </table>
    <div class="footer">
        Generated by 3D Print Pro - Total Orders: ' . count($orders) . '
    </div>
</body>
</html>';
        
        return $html;
    }
    
    protected function convertHtmlToPdf($html)
    {
        if (class_exists('TCPDF')) {
            return $this->convertWithTcpdf($html);
        }
        
        if (class_exists('Dompdf\Dompdf')) {
            return $this->convertWithDompdf($html);
        }
        
        throw new \Exception('No PDF library available. Install TCPDF or Dompdf via Composer.');
    }
    
    protected function convertWithTcpdf($html)
    {
        $pdf = new \TCPDF('L', 'mm', 'A4', true, 'UTF-8', false);
        
        $pdf->SetCreator('3D Print Pro');
        $pdf->SetAuthor('3D Print Pro');
        $pdf->SetTitle('Orders Export');
        $pdf->SetSubject('Orders Export');
        
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        
        $pdf->SetMargins(10, 10, 10);
        $pdf->SetAutoPageBreak(true, 10);
        
        $pdf->AddPage();
        
        $pdf->writeHTML($html, true, false, true, false, '');
        
        return $pdf->Output('', 'S');
    }
    
    protected function convertWithDompdf($html)
    {
        $dompdf = new \Dompdf\Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'landscape');
        $dompdf->render();
        
        return $dompdf->output();
    }
    
    public function generateSignedUrl($type, $filters = [], $fields = null, $expiresInMinutes = 60)
    {
        $data = [
            'type' => $type,
            'filters' => $filters,
            'fields' => $fields,
            'expires' => time() + ($expiresInMinutes * 60),
        ];
        
        $payload = base64_encode(json_encode($data));
        $signature = hash_hmac('sha256', $payload, $this->getSecretKey());
        
        return [
            'url' => '/api/orders/export.php?token=' . urlencode($payload) . '&sig=' . urlencode($signature),
            'expires_at' => date('Y-m-d H:i:s', $data['expires']),
        ];
    }
    
    public function validateSignedUrl($token, $signature)
    {
        $expectedSignature = hash_hmac('sha256', $token, $this->getSecretKey());
        
        if (!hash_equals($expectedSignature, $signature)) {
            return ['valid' => false, 'error' => 'Invalid signature'];
        }
        
        $data = json_decode(base64_decode($token), true);
        
        if (!$data || !isset($data['expires'])) {
            return ['valid' => false, 'error' => 'Invalid token'];
        }
        
        if (time() > $data['expires']) {
            return ['valid' => false, 'error' => 'Token expired'];
        }
        
        return [
            'valid' => true,
            'type' => $data['type'] ?? 'csv',
            'filters' => $data['filters'] ?? [],
            'fields' => $data['fields'] ?? null,
        ];
    }
    
    protected function getSecretKey()
    {
        $key = $_ENV['EXPORT_SECRET_KEY'] ?? $_SERVER['EXPORT_SECRET_KEY'] ?? null;
        
        if (!$key) {
            $key = $_ENV['DB_PASSWORD'] ?? $_SERVER['DB_PASSWORD'] ?? 'fallback-secret-key';
        }
        
        return $key;
    }
    
    public function getAvailableFields()
    {
        return [
            'id' => 'ID',
            'order_number' => 'Order Number',
            'type' => 'Type',
            'name' => 'Customer Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'telegram' => 'Telegram',
            'service' => 'Service',
            'subject' => 'Subject',
            'message' => 'Message',
            'amount' => 'Amount',
            'status' => 'Status',
            'form_slug' => 'Form',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'archived_at' => 'Archived At',
        ];
    }
}
